---
title: "bbsBayes2 SCO-SOC 2026 pre-workshop preparation"
format: pdf
editor: visual
---

## Monday, 5 October, 2026, 14:00-16:30 EDT

### **Modeling Breeding Bird Survey with bbsBayes2: status, trends, and causal modeling of drivers of trends**

Adam C. Smith (Canadian Wildlife Service, Environment and Climate Change Canada) [adam.smith\@ec.gc.ca](mailto:adam.smith@ec.gc.ca)

### bbsBayes2

[bbsBayes2](https://bbsbayes.github.io/bbsBayes2) is an R-package that allows for easy access to the North American Breeding Bird Survey data and for fitting a selection of hierarchical Bayesian models that estimate status and trends and can be modified to estimate the influence of spatial and temporal predictors on trends and abundance (e.g., [Mckellar et al. 2025](https://doi.org/10.1675/063.048.0203) and [Smith et al. 2024](https://doi.org/10.1093/ornithapp/duad056)). The package provides efficient, fully-Bayesian parameter estimation using Stan, spatially explicit models well suited to exploring spatial patterns in trends, and options to customize models to include covariates of trends and abundance. The package also allows for a streamlined Bayesian workflow that facilitates convergence diagnostics, prior and posterior predictions, visualization of model predictions, as well as cross-validation and model comparisons.

### About the workshop

During this workshop you can follow along with live coding to get hands-on experience manipulating and visualizing output from a range of models and species. We will demonstrate the package’s functions, including those that allow you to:

1.  Prepare the data for modeling a given species and fit a model that estimates trends for any time period (1970-2019, 2005-2015, 1980-2000, etc.)
2.  Generate heat maps of population trends and graph population trajectories.
3.  Choose from a suite of built-in hierarchical Bayesian models and access tools to help with cross-validation and model comparison.
4.  Estimate trends for customized regions (e.g., all of the eastern Boreal, Great Plains versus eastern populations of grassland birds).
5.  Build and fit customized models: the workshop allows some time to explore customizing the base-models with examples of models that estimate regional climate-effects on population trends, local landcover effects on mean abundance, landcover change effects on trends, etc.

## To do before the workshop

To make the workshop as efficient as possible, please ensure that you have completed the following steps prior to the workshop.

#### 1. Fill in the pre-workshop survey.

Follow [this link to answer](https://docs.google.com/forms/d/e/1FAIpQLSeEFM_nShyszyTTcwZVge8GviwxBkSJz_muyL6heIhLW2Z_Hg/viewform?usp=publish-editor) a few short questions that will help me customize the workshop.

#### 2. Install software and download BBS data

Run the installation steps at the beginning of the [Getting Started Vignette](https://bbsbayes.github.io/bbsBayes2/) including:

1.  Install the latest release of bbsBayes2 (please update if you have previously installed it)

2.  [Install cmdstanr](https://bbsbayes.github.io/bbsBayes2/articles/bbsBayes2.html#install-cmdstanr) and confirm that your setup is correct.

3.  Download the BBS data `bbsBayes2::fetch_bbs_data()`.

**If you are having problems with these installations, you're welcome to email [me](mailto:adam.smith@ec.gc.ca). I will do my best to help.**

#### 3. Download extra data (Wait 'til Friday, I'm still updating these files).

In addition, if you would like to be able to follow-along with the online coding demonstration, this [Google Drive folder](https://drive.google.com/drive/folders/1FeV2aRp9BMXWdI1qFc99-t5tQFT0RYcH?usp=sharing) will include some previously fitted models and covariate datasets. Inside the main folder are two subfolders (data and output). If you mimic this folder structure into your working directory for the workshop, you will be able run the custom models and create the custom output locally.

## Workshop plan

We will start by demonstrating some of the [basic workflow](https://bbsbayes.github.io/bbsBayes2/articles/bbsBayes2.html#workflow-overview) for using the package, largely using examples from the package vignettes. Then I'll demonstrate some ways to modify the base models to include covariates on the species' abundance or changes in abundance. The pre-workshop survey includes an option to suggest specific topics.

See you Monday!

## Français

L'atelier se déroulera en anglais. Je vous invite tous à poser vos questions dans la langue de votre choix.
